#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmartMirror.Resource", IsApplication=true)]

namespace SmartMirror
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int refreshButtonRotate = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int refreshButtonTapped = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int refresh = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int bluetoothListRowName = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int configDialogCancelButton = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int configDialogLinearLayout = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int configDialogSaveButton = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int configFieldsList = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int configHeaderText = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int configListRowName = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int mainDevicesList = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int mainHeaderText = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int mainRefreshButton = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BluetoothListRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Config = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ConfigDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ConfigListRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int configHeaderText = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int mainHeaderText = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
